// Panels
###
GET http://localhost:4000/api/panels

###
POST http://localhost:4000/api/panels
Content-Type: application/json

{
    "name": "Closed",
    "position": 3
}

###
GET http://localhost:4000/api/panels/616dbf79a615553ce68eac4f

###
PUT http://localhost:4000/api/panels/616dbf79a615553ce68eac4f
Content-Type: application/json

{
    "position": 5
}

###
DELETE http://localhost:4000/api/panels/616dbf79a615553ce68eac4f




// Work-Items
###
GET http://localhost:4000/api/workitems

###
POST http://localhost:4000/api/workitems
Content-Type: application/json

{
    "name": "Walk dog",
    "panel": "Doing",
    "position": 4
}

###
GET http://localhost:4000/api/workitems/615de802b4719e1dbb786f66

###
PUT http://localhost:4000/api/workitems/615f2118b0cc9646f1f4a090
Content-Type: application/json

{
    "panel": "Done"
}

###
DELETE http://localhost:4000/api/workitems/615de802b4719e1dbb786f66