// Panels
###
GET http://localhost:4000/api/panels

###
POST http://localhost:4000/api/panels
Content-Type: application/json

{
    "name": "Close",
    "position": 4
}

###
GET http://localhost:4000/api/panels/615f38f434f2c45eaca3d019

###
PUT http://localhost:4000/api/panels/615f3a3134f2c45eaca3d02a
Content-Type: application/json

{
    "position": 2
}

###
DELETE http://localhost:4000/api/panels/616024919a8b70ff924341e1




// Work-Items
###
GET http://localhost:4000/api/workitems

###
POST http://localhost:4000/api/workitems
Content-Type: application/json

{
    "name": "Walk dog",
    "panel": "Doing",
    "position": 5
}

###
GET http://localhost:4000/api/workitems/615de802b4719e1dbb786f66

###
PUT http://localhost:4000/api/workitems/615f2118b0cc9646f1f4a090
Content-Type: application/json

{
    "panel": "Done"
}

###
DELETE http://localhost:4000/api/workitems/615de802b4719e1dbb786f66